// Generated by CoffeeScript 1.7.1
var Hooks;

Hooks = (function() {
  function Hooks() {}

  Hooks.post_install = function() {};

  Hooks.post_update = function(previous_version) {};

  Hooks.post_chrome_update = function() {};

  Hooks.post_startup = function() {};

  return Hooks;

})();

chrome.runtime.onInstalled.addListener(function(details) {
  switch (details.reason) {
    case "install":
      return Hooks.post_install();
    case "update":
      return Hooks.post_update(details.previousVersion);
    case "chrome_update":
      return Hooks.post_chrome_update();
  }
});

chrome.runtime.onStartup.addListener(function() {
  return console.log("Booting Youtoo Tools");
});
