// Generated by CoffeeScript 1.7.1
$(function() {
  $('#action-cache-clear').click(function() {});
  $('#action-cache-disable').click(function() {
    $(this).addClass("none");
    return $("#action-cache-enable").removeClass("none");
  });
  $('#action-cache-enable').click(function() {
    $(this).addClass("none");
    return $("#action-cache-disable").removeClass("none");
  });
  $('#action-cookies-clear').click(function() {});
  return $('#action-incognito-create').click(function() {});
});
